version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

#docker exec -it postgres bash
#psql -d appdb -U postgres